# Data adapted from https://www.kaggle.com/datasets/polartech/walmart-grocery-product-dataset
PRODUCT_DB = [
    {
        "department": "Deli",
        "product_name": "Original Sliced Honey Ham",
        "size": "2 Oz.",
        "brand": "Buddig",
        "price": 0.8,
        "aisle": 5,
        "stock": 7,
    },
    {
        "department": "Deli",
        "product_name": "Colby Jack Cheese",
        "size": "1 package",
        "brand": "Prima Della",
        "price": 8.64,
        "aisle": 2,
        "stock": 12,
    },
    {
        "department": "Deli",
        "product_name": "Corned Beef",
        "size": "1 package",
        "brand": "Prima Della",
        "price": 11.87,
        "aisle": 11,
        "stock": 5,
    },
    {
        "department": "Deli",
        "product_name": "Swiss Cheese",
        "size": "50g",
        "brand": "Kerrygold",
        "price": 5.28,
        "aisle": 5,
        "stock": 9,
    },
    {
        "department": "Deli",
        "product_name": "Swiss Cheese",
        "size": "173g",
        "brand": "Great Value",
        "price": 11.28,
        "aisle": 5,
        "stock": 3,
    },
    {
        "department": "Deli",
        "product_name": "Deli Sliced Garlic Bologna",
        "size": "1 package",
        "brand": "Eckrich",
        "price": 5.12,
        "aisle": 6,
        "stock": 14,
    },
    {
        "department": "Deli",
        "product_name": "Sweet Kale Chopped Salad Kit",
        "size": "12 oz",
        "brand": "Taylor Farms",
        "price": 3.98,
        "aisle": 11,
        "stock": 8,
    },
    {
        "department": "Deli",
        "product_name": "Nashville Inspired Hot Chicken Pizza",
        "size": "25.8 oz (Fresh)",
        "brand": "Marketside",
        "price": 7.0,
        "aisle": 4,
        "stock": 6,
    },
    {
        "department": "Deli",
        "product_name": "Hottie Bites",
        "size": "3.25 FL oz",
        "brand": "OH SNAP!",
        "price": 1.47,
        "aisle": 10,
        "stock": 22,
    },
    {
        "department": "Deli",
        "product_name": "Beef Bologna Deli Lunch Meat",
        "size": "16 oz Package",
        "brand": "Oscar Mayer",
        "price": 6.84,
        "aisle": 14,
        "stock": 11,
    },
    {
        "department": "Beverages",
        "product_name": "Organic Honey Lemon Daily Wellness Tea Bags",
        "size": "12 Ct",
        "brand": "Celestial Seasonings",
        "price": 3.44,
        "aisle": 2,
        "stock": 17,
    },
    {
        "department": "Beverages",
        "product_name": "Punched Watermelon Energy Drink",
        "size": "16 oz",
        "brand": "Rockstar",
        "price": 1.88,
        "aisle": 9,
        "stock": 30,
    },
    {
        "department": "Beverages",
        "product_name": "100% Carrot Vegetable Juice",
        "size": "11 oz",
        "brand": "Bolthouse Farms",
        "price": 2.18,
        "aisle": 8,
        "stock": 13,
    },
    {
        "department": "Beverages",
        "product_name": "Jammers Cherry Artificially Flavored Drink",
        "size": "10 ct Box, 6 oz Pouches",
        "brand": "Kool-Aid",
        "price": 2.5,
        "aisle": 5,
        "stock": 16,
    },
    {
        "department": "Beverages",
        "product_name": "100% Arabica Colombian Medium Dark Ground Coffee",
        "size": "24.2 oz",
        "brand": "Great Value",
        "price": 9.76,
        "aisle": 13,
        "stock": 10,
    },
    {
        "department": "Beverages",
        "product_name": "Energy Drink",
        "size": "8.4 Fl Oz (4 pack)",
        "brand": "Red Bull",
        "price": 7.24,
        "aisle": 3,
        "stock": 28,
    },
    {
        "department": "Beverages",
        "product_name": "Energy Drink",
        "size": "16 oz",
        "brand": "Rockstar",
        "price": 1.88,
        "aisle": 6,
        "stock": 25,
    },
    {
        "department": "Beverages",
        "product_name": "100% Pomegranate Juice",
        "size": "48 Fl Oz",
        "brand": "Pom Wonderful",
        "price": 9.48,
        "aisle": 15,
        "stock": 7,
    },
    {
        "department": "Beverages",
        "product_name": "100% Apple Juice",
        "size": "64 Oz.",
        "brand": "Great Value",
        "price": 1.62,
        "aisle": 4,
        "stock": 20,
    },
    {
        "department": "Beverages",
        "product_name": "100% Apple Juice",
        "size": "42 Oz.",
        "brand": "Great Value",
        "price": 1.33,
        "aisle": 4,
        "stock": 3,
    },
    {
        "department": "Beverages",
        "product_name": "100% Apple Juice",
        "size": "36 Oz.",
        "brand": "Great Value",
        "price": 0.94,
        "aisle": 4,
        "stock": 26,
    },
    {
        "department": "Baking",
        "product_name": "Aqua Blue Vanilla Frosting",
        "size": "15.6 Oz Tub",
        "brand": "Pillsbury",
        "price": 1.74,
        "aisle": 16,
        "stock": 15,
    },
    {
        "department": "Baking",
        "product_name": "Organic Unbleached White All-Purpose Flour",
        "size": "5 lbs",
        "brand": "Bob's Red Mill",
        "price": 7.58,
        "aisle": 12,
        "stock": 9,
    },
    {
        "department": "Baking",
        "product_name": "Active Dry Yeast",
        "size": "0.75 Oz, 3 Pack",
        "brand": "Fleischmann's",
        "price": 1.72,
        "aisle": 2,
        "stock": 23,
    },
    {
        "department": "Baking",
        "product_name": "Frozen Coconut Flakes",
        "size": "6 Oz",
        "brand": "Birdseye",
        "price": 1.62,
        "aisle": 8,
        "stock": 11,
    },
    {
        "department": "Baking",
        "product_name": "100% Extra Virgin Olive Oil",
        "size": "8.5 oz",
        "brand": "Iberia",
        "price": 3.26,
        "aisle": 16,
        "stock": 18,
    },
    {
        "department": "Baking",
        "product_name": "Chocolate Chunk Muffin Mix",
        "size": "18.25 OZ Box",
        "brand": "Krusteaz",
        "price": 2.97,
        "aisle": 6,
        "stock": 14,
    },
    {
        "department": "Baking",
        "product_name": "Organic Coconut Flour",
        "size": "36 oz",
        "brand": "Great Value Organic",
        "price": 7.83,
        "aisle": 13,
        "stock": 8,
    },
    {
        "department": "Baking",
        "product_name": "Easy Pumpkin Pie Mix",
        "size": "30 oz",
        "brand": "Libby's",
        "price": 3.28,
        "aisle": 10,
        "stock": 6,
    },
    {
        "department": "Baking",
        "product_name": "Vanilla Frosting",
        "size": "15.6 Oz Tub",
        "brand": "Pillsbury",
        "price": 1.74,
        "aisle": 15,
        "stock": 15,
    },
    {
        "department": "Baking",
        "product_name": "Gluten Free Chocolate Frosting",
        "size": "16 oz",
        "brand": "Betty Crocker",
        "price": 1.58,
        "aisle": 9,
        "stock": 12,
    },
    {
        "department": "Meat & Seafood",
        "product_name": "Black Bean Burger Patties Plant Based",
        "size": "1/4 lb 2Ct",
        "brand": "Gardein",
        "price": 3.84,
        "aisle": 2,
        "stock": 10,
    },
    {
        "department": "Meat & Seafood",
        "product_name": "Peeled Tail on Extra Large Shrimp",
        "size": "12 Oz ",
        "brand": "Walmart Seafood",
        "price": 5.84,
        "aisle": 8,
        "stock": 7,
    },
    {
        "department": "Meat & Seafood",
        "product_name": "All Natural Fresh Bone In Chicken Thighs",
        "size": "4.75 - 6.0 lb",
        "brand": "Tyson",
        "price": 9.89,
        "aisle": 4,
        "stock": 16,
    },
    {
        "department": "Meat & Seafood",
        "product_name": "Cracked Pepper Turkey Breast",
        "size": "1 package1 package",
        "brand": "Prima Della",
        "price": 5.44,
        "aisle": 14,
        "stock": 5,
    },
    {
        "department": "Meat & Seafood",
        "product_name": "Meatloaf with Tomato Sauce Refrigerated Entre",
        "size": "15 oz",
        "brand": "Hormel",
        "price": 6.97,
        "aisle": 10,
        "stock": 9,
    },
    {
        "department": "Meat & Seafood",
        "product_name": "Country Style Ribs",
        "size": "1.25 - 2.99 lb",
        "brand": "Fresh Beef",
        "price": 12.2,
        "aisle": 16,
        "stock": 4,
    },
    {
        "department": "Meat & Seafood",
        "product_name": "Beef Smoked Sausage Links",
        "size": "13.5 oz, 6 Ct",
        "brand": "Hillshire Farm",
        "price": 2.98,
        "aisle": 14,
        "stock": 13,
    },
    {
        "department": "Meat & Seafood",
        "product_name": "Italian Garlic & Fennel Plant-Based Sausage",
        "size": "1 package",
        "brand": "Field Roast",
        "price": 5.33,
        "aisle": 13,
        "stock": 8,
    },
    {
        "department": "Meat & Seafood",
        "product_name": "Hot Italian Pork Sausage",
        "size": "19 oz., 1.19lb. (Fresh)",
        "brand": "Premio Foods",
        "price": 4.78,
        "aisle": 1,
        "stock": 11,
    },
    {
        "department": "Candy",
        "product_name": "Mexican Chili Lollipops",
        "size": "15.8 oz Bag",
        "brand": "Gudu",
        "price": 2.97,
        "aisle": 2,
        "stock": 17,
    },
    {
        "department": "Candy",
        "product_name": "Polar Ice Sugar Free Chewing Gum",
        "size": "15 ct (3 Pack)",
        "brand": "Extra",
        "price": 3.48,
        "aisle": 5,
        "stock": 24,
    },
    {
        "department": "Candy",
        "product_name": "Milk Chocolate with Almonds Bar",
        "size": "1.45 Oz",
        "brand": "Hershey's",
        "price": 1.14,
        "aisle": 11,
        "stock": 35,
    },
    {
        "department": "Candy",
        "product_name": "Twist 4 Assorted Flavors Gum",
        "size": "16 Oz",
        "brand": "Dubble Bubble",
        "price": 2.68,
        "aisle": 2,
        "stock": 19,
    },
    {
        "department": "Candy",
        "product_name": "Pink Buttermints",
        "size": "2.75 lbs",
        "brand": "Party Sweets",
        "price": 10.14,
        "aisle": 12,
        "stock": 6,
    },
    {
        "department": "Candy",
        "product_name": "Halloween Candy Variety Pack",
        "size": "170 Ct Bag, 62.02oz",
        "brand": "Mixed",
        "price": 16.98,
        "aisle": 4,
        "stock": 22,
    },
    {
        "department": "Candy",
        "product_name": "Chewy Candy Sticks",
        "size": "7.78 oz 21ct",
        "brand": "Starburst",
        "price": 3.78,
        "aisle": 16,
        "stock": 18,
    },
    {
        "department": "Snacks",
        "product_name": "Organic Sesame Street Peanut Butter Baked Corn Puffs",
        "size": "2.5 oz Bag",
        "brand": "Earth's Best",
        "price": 3.63,
        "aisle": 11,
        "stock": 13,
    },
    {
        "department": "Snacks",
        "product_name": "Potato Crisps Chips, Variety Pack",
        "size": "16 Ct, 22 Oz, Pack",
        "brand": "Pringles",
        "price": 13.16,
        "aisle": 8,
        "stock": 9,
    },
    {
        "department": "Snacks",
        "product_name": "Chunky Habanero Salsa",
        "size": "15.5 oz Jar",
        "brand": "Tostitos",
        "price": 5.38,
        "aisle": 4,
        "stock": 16,
    },
    {
        "department": "Snacks",
        "product_name": "Caramel Almond & Sea Salt",
        "size": "1.4 Oz, 12 Count",
        "brand": "KIND Bars",
        "price": 15.46,
        "aisle": 4,
        "stock": 7,
    },
    {
        "department": "Snacks",
        "product_name": "Gluten-Free Sea Salt Microwave Popcorn",
        "size": "2.8 oz, 6 Count",
        "brand": "SkinnyPop",
        "price": 4.84,
        "aisle": 11,
        "stock": 18,
    },
    {
        "department": "Snacks",
        "product_name": "Beef Jerky, Hickory Smoked",
        "size": "2.85oz",
        "brand": "Jack Link's",
        "price": 4.98,
        "aisle": 3,
        "stock": 11,
    },
    {
        "department": "Snacks",
        "product_name": "Glacier Ranch Tortilla Chips",
        "size": "9.75 oz",
        "brand": "Great Value",
        "price": 1.74,
        "aisle": 2,
        "stock": 27,
    },
    {
        "department": "Dairy & Eggs",
        "product_name": "Skyr, Coconut",
        "size": "5.3 Ounce",
        "brand": "Icelandic Provisions",
        "price": 1.48,
        "aisle": 1,
        "stock": 14,
    },
    {
        "department": "Dairy & Eggs",
        "product_name": "Strawberry Cheesecake Snacks",
        "size": "2 ct Pack, 3.25 oz Cups",
        "brand": "Philadelphia",
        "price": 2.98,
        "aisle": 8,
        "stock": 0,
    },
    {
        "department": "Dairy & Eggs",
        "product_name": "Light Spread",
        "size": "15 oz",
        "brand": "I Can't Believe It's Not Butter!",
        "price": 3.98,
        "aisle": 4,
        "stock": 9,
    },
    {
        "department": "Dairy & Eggs",
        "product_name": "Butter with Olive Oil and Sea Salt",
        "size": "7 oz",
        "brand": "Land O'Lakes",
        "price": 2.37,
        "aisle": 16,
        "stock": 18,
    },
    {
        "department": "Dairy & Eggs",
        "product_name": "Liquid Hazelnut Sugar Free Coffee Creamer",
        "size": "32 oz",
        "brand": "Coffeemate",
        "price": 3.98,
        "aisle": 2,
        "stock": 11,
    },
    {
        "department": "Dairy & Eggs",
        "product_name": "Organic YoBaby Apple & Blueberry Baby Yogurt with Probiotics",
        "size": "6-4 oz. Cups",
        "brand": "Stonyfield Farm",
        "price": 4.33,
        "aisle": 16,
        "stock": 7,
    },
    {
        "department": "Bakery & Bread",
        "product_name": "Small Fajita Flour Tortillas",
        "size": "22.5 oz",
        "brand": "Great Value",
        "price": 1.98,
        "aisle": 15,
        "stock": 22,
    },
    {
        "department": "Bakery & Bread",
        "product_name": "Gluten Free Bread",
        "size": "18 oz Loaf",
        "brand": "Canyon Bakehouse",
        "price": 6.18,
        "aisle": 8,
        "stock": 6,
    },
    {
        "department": "Bakery & Bread",
        "product_name": "Plain Cake Donuts",
        "size": "2 Count",
        "brand": "Freshness Guaranteed",
        "price": 1.46,
        "aisle": 2,
        "stock": 18,
    },
    {
        "department": "Bakery & Bread",
        "product_name": "Pecan Tiny Pies",
        "size": "16.2 oz, 16 Count",
        "brand": "Freshness Guaranteed",
        "price": 5.94,
        "aisle": 2,
        "stock": 10,
    },
    {
        "department": "Bakery & Bread",
        "product_name": "Whole Grains Healthy Multi-Grain Bread",
        "size": "24 oz",
        "brand": "Arnold",
        "price": 3.97,
        "aisle": 4,
        "stock": 14,
    },
    {
        "department": "Bakery & Bread",
        "product_name": "Sesame French Bread",
        "size": "14 oz",
        "brand": "Freshness Guaranteed",
        "price": 1.78,
        "aisle": 16,
        "stock": 20,
    },
    {
        "department": "Bakery & Bread",
        "product_name": "SNOBALLS Single Serve",
        "size": "2 count, 3.5 oz",
        "brand": "Hostess",
        "price": 1.58,
        "aisle": 4,
        "stock": 26,
    },
    {
        "department": "Bakery & Bread",
        "product_name": "Vanilla Strawberry Ice Cream Krunch Cake",
        "size": "40 oz",
        "brand": "Friendly's",
        "price": 14.98,
        "aisle": 2,
        "stock": 5,
    },
    {
        "department": "Bakery & Bread",
        "product_name": "Assorted Sweet Rolls",
        "size": "24 oz, 6 Rolls",
        "brand": "Freshness Guaranteed",
        "price": 3.98,
        "aisle": 14,
        "stock": 15,
    },
    {
        "department": "Bakery & Bread",
        "product_name": "Texas Toast Bread",
        "size": "22 oz.",
        "brand": "Aunt Millie's",
        "price": 2.14,
        "aisle": 10,
        "stock": 17,
    },
    {
        "department": "Breakfast & Cereal",
        "product_name": "Green Tea, Lemon Ginseng",
        "size": "1 package",
        "brand": "Lipton",
        "price": 2.78,
        "aisle": 5,
        "stock": 19,
    },
    {
        "department": "Breakfast & Cereal",
        "product_name": "Queso Fresco Fresh Crumbling Cheese",
        "size": "24 Oz",
        "brand": "La Morenita",
        "price": 6.22,
        "aisle": 8,
        "stock": 8,
    },
    {
        "department": "Breakfast & Cereal",
        "product_name": "Old Fashioned Oatmeal, Whole Grain",
        "size": "42 oz",
        "brand": "Quaker",
        "price": 5.68,
        "aisle": 1,
        "stock": 13,
    },
    {
        "department": "Breakfast & Cereal",
        "product_name": "Instant Oatmeal, Variety",
        "size": "12.1 Oz, 12 Count",
        "brand": "Quaker",
        "price": 3.23,
        "aisle": 8,
        "stock": 16,
    },
    {
        "department": "Breakfast & Cereal",
        "product_name": "Mini Croissants, Chocolate, Non-GMO",
        "size": "2.29oz (Pack of 4 Pouches)",
        "brand": "7DAYS",
        "price": 3.68,
        "aisle": 1,
        "stock": 21,
    },
    {
        "department": "Breakfast & Cereal",
        "product_name": "Original Cream Cheese Spread",
        "size": "12 oz Tub",
        "brand": "Philadelphia",
        "price": 5.78,
        "aisle": 6,
        "stock": 11,
    },
    {
        "department": "Breakfast & Cereal",
        "product_name": "Go-Gurt, Low Fat Yogurt, Berry & Strawberry Variety Pack",
        "size": "32 oz",
        "brand": "Yoplait",
        "price": 4.97,
        "aisle": 6,
        "stock": 14,
    },
    {
        "department": "Breakfast & Cereal",
        "product_name": "100% Orange Juice",
        "size": "64 oz",
        "brand": "Great Value",
        "price": 2.98,
        "aisle": 13,
        "stock": 23,
    },
    {
        "department": "Breakfast & Cereal",
        "product_name": "Organic Whipped Buttery Spread",
        "size": "13 oz.",
        "brand": "Earth Balance",
        "price": 5.73,
        "aisle": 2,
        "stock": 9,
    },
    {
        "department": "Breakfast & Cereal",
        "product_name": "Croissant Sandwiches Sausage Egg and Cheese",
        "size": "4 Count",
        "brand": "Great Value",
        "price": 5.78,
        "aisle": 3,
        "stock": 0,
    },
    {
        "department": "Pantry",
        "product_name": "Zesty Robusto Italian Dressing",
        "size": "15 oz",
        "brand": "Wish-Bone",
        "price": 2.58,
        "aisle": 9,
        "stock": 15,
    },
    {
        "department": "Pantry",
        "product_name": "Sunny Cranberry Pepitas Salad Topping",
        "size": "5.5oz",
        "brand": "Salad Pizazz!",
        "price": 2.98,
        "aisle": 3,
        "stock": 10,
    },
    {
        "department": "Pantry",
        "product_name": "Chipotle Peppers in Adobo Sauce",
        "size": "7.0 oz",
        "brand": "GOYA",
        "price": 2.18,
        "aisle": 8,
        "stock": 18,
    },
    {
        "department": "Pantry",
        "product_name": "Real Bacon Pieces",
        "size": "9 oz",
        "brand": "Great Value",
        "price": 5.72,
        "aisle": 15,
        "stock": 12,
    },
    {
        "department": "Pantry",
        "product_name": "Peach Halves",
        "size": "29 oz Can",
        "brand": "Great Value",
        "price": 2.44,
        "aisle": 10,
        "stock": 16,
    },
    {
        "department": "Pantry",
        "product_name": "Mango Habanero",
        "size": "1 package",
        "brand": "Buffalo Wild Wings",
        "price": 3.58,
        "aisle": 5,
        "stock": 11,
    },
    {
        "department": "Pantry",
        "product_name": "Organic Creamy California Raw Almond Butter",
        "size": "12 oz",
        "brand": "MaraNatha",
        "price": 16.84,
        "aisle": 4,
        "stock": 5,
    },
    {
        "department": "Pantry",
        "product_name": "Southwest Style Salad with Chicken",
        "size": "1 package",
        "brand": "Marketside",
        "price": 4.47,
        "aisle": 2,
        "stock": 8,
    },
    {
        "department": "Pantry",
        "product_name": "Mediterranean Pitted Olive Mix",
        "size": "1 package",
        "brand": "Asaro",
        "price": 5.99,
        "aisle": 9,
        "stock": 7,
    },
    {
        "department": "Coffee",
        "product_name": "Vanilla Flavored Coffee, Ground Coffee",
        "size": "11 oz",
        "brand": "Starbucks",
        "price": 8.98,
        "aisle": 14,
        "stock": 13,
    },
    {
        "department": "Coffee",
        "product_name": "Baking Blend, Sugar Substitute",
        "size": "12 oz. Bag",
        "brand": "Whole Earth Sweetener",
        "price": 7.68,
        "aisle": 15,
        "stock": 8,
    },
    {
        "department": "Coffee",
        "product_name": "Organic Powdered Raw Cane Sugar",
        "size": "16 oz Pouch",
        "brand": "Florida Crystals",
        "price": 3.12,
        "aisle": 14,
        "stock": 20,
    },
    {
        "department": "Coffee",
        "product_name": "Cold Cup with Cold Brew Birthday Everyday Gift",
        "size": "1 package",
        "brand": "Starbucks",
        "price": 13.98,
        "aisle": 14,
        "stock": 4,
    },
    {
        "department": "Coffee",
        "product_name": "French Vanilla Instant Cappuccino Coffee Drink Mix",
        "size": "16 Oz Canister",
        "brand": "Hills Bros. Coffee",
        "price": 3.72,
        "aisle": 13,
        "stock": 0,
    },
    {
        "department": "Coffee",
        "product_name": "Caramel Macchiato Iced Coffee",
        "size": "64 Oz.",
        "brand": "International Delight",
        "price": 4.28,
        "aisle": 8,
        "stock": 14,
    },
    {
        "department": "Coffee",
        "product_name": "French Vanilla Coffee Creamer Singles",
        "size": "48 Count",
        "brand": "International Delight",
        "price": 5.12,
        "aisle": 11,
        "stock": 19,
    },
    {
        "department": "Frozen",
        "product_name": "Dark Sweet Cherries, Frozen, Pitted",
        "size": "16 oz",
        "brand": "Great Value",
        "price": 3.88,
        "aisle": 12,
        "stock": 17,
    },
    {
        "department": "Frozen",
        "product_name": "Dairy Free Meatless Pepperoni Gluten Free Pizza",
        "size": "16.7oz",
        "brand": "Daiya",
        "price": 6.94,
        "aisle": 13,
        "stock": 9,
    },
    {
        "department": "Frozen",
        "product_name": "Ezekiel 4:9 Sprouted Whole Grain Bread",
        "size": "24oz",
        "brand": "Food for Life",
        "price": 6.18,
        "aisle": 9,
        "stock": 6,
    },
    {
        "department": "Frozen",
        "product_name": "Home Menu Chicken Lo Mein Skillet Meal",
        "size": "22 OZ",
        "brand": "P.F. Chang's",
        "price": 7.78,
        "aisle": 15,
        "stock": 0,
    },
    {
        "department": "Frozen",
        "product_name": "Cauliflower Crust Margherita",
        "size": "1 package",
        "brand": "Great Value",
        "price": 4.96,
        "aisle": 9,
        "stock": 10,
    },
    {
        "department": "Frozen",
        "product_name": "100% Beef Sliced Steaks",
        "size": "31.5 oz",
        "brand": "Steak-umm",
        "price": 10.56,
        "aisle": 1,
        "stock": 8,
    },
    {
        "department": "Frozen",
        "product_name": "Big Burrito Red Hot Beef",
        "size": "1 package",
        "brand": "Tina's",
        "price": 1.27,
        "aisle": 2,
        "stock": 28,
    },
    {
        "department": "Frozen",
        "product_name": "Pizza Rolls, Triple Cheese Flavored",
        "size": "24.8 oz",
        "brand": "Totino's",
        "price": 4.98,
        "aisle": 11,
        "stock": 0,
    },
    {
        "department": "Frozen",
        "product_name": "Supreme, Rising Crust Pizza",
        "size": "31.4 oz",
        "brand": "DiGiorno",
        "price": 6.92,
        "aisle": 16,
        "stock": 14,
    },
    {
        "department": "Fresh Produce",
        "product_name": "Watermelon Chunks",
        "size": "42 oz",
        "brand": "Marketside",
        "price": 8.97,
        "aisle": 7,
        "stock": 6,
    },
    {
        "department": "Fresh Produce",
        "product_name": "Organic Garlic Sleeve",
        "size": "3 Count",
        "brand": "Spice World",
        "price": 2.98,
        "aisle": 8,
        "stock": 15,
    },
    {
        "department": "Fresh Produce",
        "product_name": "Napa Cabbage",
        "size": "1 item",
        "brand": "No Name",
        "price": 3.97,
        "aisle": 4,
        "stock": 9,
    },
    {
        "department": "Fresh Produce",
        "product_name": "Rose Plus Bouquet",
        "size": "1 bunch",
        "brand": "No Name",
        "price": 9.97,
        "aisle": 4,
        "stock": 4,
    },
    {
        "department": "Fresh Produce",
        "product_name": "Organic Asparagus",
        "size": "1 bunch",
        "brand": "No Name",
        "price": 5.96,
        "aisle": 8,
        "stock": 7,
    },
    {
        "department": "Fresh Produce",
        "product_name": "Chunky Blue Cheese Dressing & Dip",
        "size": "13 oz Jar",
        "brand": "Litehouse",
        "price": 3.96,
        "aisle": 5,
        "stock": 11,
    },
    {
        "department": "Fresh Produce",
        "product_name": "Minced Garlic",
        "size": "32 Oz",
        "brand": "Great Value",
        "price": 7.76,
        "aisle": 13,
        "stock": 19,
    },
    {
        "department": "Fresh Produce",
        "product_name": "White Nectarines",
        "size": "1 item",
        "brand": "No Name",
        "price": 1.06,
        "aisle": 11,
        "stock": 8,
    },
    {
        "department": "Fresh Produce",
        "product_name": "Fresh Long English Cucumber",
        "size": "1 item",
        "brand": "No Name",
        "price": 1.38,
        "aisle": 8,
        "stock": 12,
    },
    {
        "department": "Alcohol",
        "product_name": "Beer",
        "size": "30 Pack 12 oz",
        "brand": "Bud Ice",
        "price": 19.98,
        "aisle": 13,
        "stock": 18,
    },
    {
        "department": "Alcohol",
        "product_name": "Hard Seltzer Variety Pack 1",
        "size": "12 Pack, 12 oz Cans",
        "brand": "Vizzy",
        "price": 17.98,
        "aisle": 9,
        "stock": 14,
    },
    {
        "department": "Alcohol",
        "product_name": "Bourbon Barrel Aged Cabernet Sauvignon Red Wine",
        "size": "750 mL Bottle",
        "brand": "Robert Mondavi Private Selection",
        "price": 11.98,
        "aisle": 13,
        "stock": 9,
    },
    {
        "department": "Alcohol",
        "product_name": "White Wine",
        "size": "3 L Box",
        "brand": "Black Box",
        "price": 18.98,
        "aisle": 8,
        "stock": 7,
    },
    {
        "department": "Alcohol",
        "product_name": "Cabernet Sauvignon Wine",
        "size": "750 mL",
        "brand": "JUSTIN",
        "price": 24.48,
        "aisle": 14,
        "stock": 5,
    },
    {
        "department": "Alcohol",
        "product_name": "Beer",
        "size": "6 Pack, 16 oz Cans",
        "brand": "Old Style",
        "price": 6.73,
        "aisle": 14,
        "stock": 20,
    },
    {
        "department": "Alcohol",
        "product_name": "Petit Petite Wine",
        "size": "750 mL",
        "brand": "Michael David Winery",
        "price": 13.48,
        "aisle": 11,
        "stock": 6,
    },
    {
        "department": "Alcohol",
        "product_name": "Prosecco Sparkling White Wine",
        "size": "375ml",
        "brand": "LA MARCA",
        "price": 9.98,
        "aisle": 14,
        "stock": 11,
    },
    {
        "department": "Alcohol",
        "product_name": "Merlot Wine",
        "size": "1.5 L",
        "brand": "Barefoot",
        "price": 9.98,
        "aisle": 4,
        "stock": 8,
    },
    {
        "department": "Alcohol",
        "product_name": "Light Beer",
        "size": "30 Pack, 12 oz Cans",
        "brand": "Keystone",
        "price": 17.99,
        "aisle": 3,
        "stock": 0,
    },
]


