/*
    Copyright 2026 Picovoice Inc.

    You may not use this file except in compliance with the license. A copy of the license is
    located in the "LICENSE" file accompanying this source.

    Unless required by applicable law or agreed to in writing, software distributed under the
    License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
    express or implied. See the License for the specific language governing permissions and
    limitations under the License.
*/

package ai.picovoice.retailassociate;

import android.view.LayoutInflater;
import android.view.View;
import android.widget.TextView;
import android.widget.LinearLayout;

import java.util.ArrayList;

public class Product {
    String department;
    String productName;
    String size;
    String brand;
    float price;
    int aisle;
    int stock;

    String lookupName;
    String lookupBrand;

    public Product(
            String department,
            String productName,
            String size,
            String brand,
            float price,
            int aisle,
            int stock) {
        this.department = department;
        this.productName = productName;
        this.size = size;
        this.brand = brand;
        this.price = price;
        this.aisle = aisle;
        this.stock = stock;

        this.lookupName = "";
        for (char ch :
            productName
            .replace("&", "and")
            .replace("100%", "one hundred percent")
            .replace("-", " ")
            .replace("4:9", "four nine")
            .replace("4", "four")
            .replace("1", "one")
            .replace("Buttermints", "Butter mints")
            .replace("YoBaby", "Yo Baby")
            .replace("SNOBALLS", "Snow balls")
            .replace("Krunch", "crunch")
        ) {
            if (ch == '!' || ch == ",") {
                continue;
            }

            this.lookupName += ch;
        }

        if (PRONUNCIATION_MAP.containsKey(this.brand)) {
            this.lookupBrand = PRONUNCIATION_MAP.get(product.brand);
        } else {
            this.lookupBrand = "";
            for (char ch : productName) {
                if (ch == '!' || ch == "7" || ch == ".") {
                    continue;
                }

                this.lookupBrand += ch;
            }
        }
    }

    // Data adapted from https://www.kaggle.com/datasets/polartech/walmart-grocery-Product-dataset
    public static final ArrayList<Product> PRODUCT_DB = new ArrayList(
        new Product(
            "Deli",
            "Original Sliced Honey Ham",
            "2 Oz.",
            "Buddig",
            0.8,
            5,
            7,
        ),
        new Product(
            "Deli",
            "Colby Jack Cheese",
            "1 package",
            "Prima Della",
            8.64,
            2,
            12,
        ),
        new Product(
            "Deli",
            "Corned Beef",
            "1 package",
            "Prima Della",
            11.87,
            11,
            5,
        ),
        new Product(
            "Deli",
            "Swiss Cheese",
            "50g",
            "Kerrygold",
            5.28,
            5,
            9,
        ),
        new Product(
            "Deli",
            "Swiss Cheese",
            "173g",
            "Great Value",
            11.28,
            5,
            3,
        ),
        new Product(
            "Deli",
            "Deli Sliced Garlic Bologna",
            "1 package",
            "Eckrich",
            5.12,
            6,
            14,
        ),
        new Product(
            "Deli",
            "Sweet Kale Chopped Salad Kit",
            "12 oz",
            "Taylor Farms",
            3.98,
            11,
            8,
        ),
        new Product(
            "Deli",
            "Nashville Inspired Hot Chicken Pizza",
            "25.8 oz (Fresh)",
            "Marketside",
            7.0,
            4,
            6,
        ),
        new Product(
            "Deli",
            "Hottie Bites",
            "3.25 FL oz",
            "OH SNAP!",
            1.47,
            10,
            22,
        ),
        new Product(
            "Deli",
            "Beef Bologna Deli Lunch Meat",
            "16 oz Package",
            "Oscar Mayer",
            6.84,
            14,
            11,
        ),
        new Product(
            "Beverages",
            "Organic Honey Lemon Daily Wellness Tea Bags",
            "12 Ct",
            "Celestial Seasonings",
            3.44,
            2,
            17,
        ),
        new Product(
            "Beverages",
            "Punched Watermelon Energy Drink",
            "16 oz",
            "Rockstar",
            1.88,
            9,
            30,
        ),
        new Product(
            "Beverages",
            "100% Carrot Vegetable Juice",
            "11 oz",
            "Bolthouse Farms",
            2.18,
            8,
            13,
        ),
        new Product(
            "Beverages",
            "Jammers Cherry Artificially Flavored Drink",
            "10 ct Box, 6 oz Pouches",
            "Kool-Aid",
            2.5,
            5,
            16,
        ),
        new Product(
            "Beverages",
            "100% Arabica Colombian Medium Dark Ground Coffee",
            "24.2 oz",
            "Great Value",
            9.76,
            13,
            10,
        ),
        new Product(
            "Beverages",
            "Energy Drink",
            "8.4 Fl Oz (4 pack)",
            "Red Bull",
            7.24,
            3,
            28,
        ),
        new Product(
            "Beverages",
            "Energy Drink",
            "16 oz",
            "Rockstar",
            1.88,
            6,
            25,
        ),
        new Product(
            "Beverages",
            "100% Pomegranate Juice",
            "48 Fl Oz",
            "Pom Wonderful",
            9.48,
            15,
            7,
        ),
        new Product(
            "Beverages",
            "100% Apple Juice",
            "64 Oz.",
            "Great Value",
            1.62,
            4,
            20,
        ),
        new Product(
            "Beverages",
            "100% Apple Juice",
            "42 Oz.",
            "Great Value",
            1.33,
            4,
            3,
        ),
        new Product(
            "Beverages",
            "100% Apple Juice",
            "36 Oz.",
            "Great Value",
            0.94,
            4,
            26,
        ),
        new Product(
            "Baking",
            "Aqua Blue Vanilla Frosting",
            "15.6 Oz Tub",
            "Pillsbury",
            1.74,
            16,
            15,
        ),
        new Product(
            "Baking",
            "Organic Unbleached White All-Purpose Flour",
            "5 lbs",
            "Bob's Red Mill",
            7.58,
            12,
            9,
        ),
        new Product(
            "Baking",
            "Active Dry Yeast",
            "0.75 Oz, 3 Pack",
            "Fleischmann's",
            1.72,
            2,
            23,
        ),
        new Product(
            "Baking",
            "Frozen Coconut Flakes",
            "6 Oz",
            "Birdseye",
            1.62,
            8,
            11,
        ),
        new Product(
            "Baking",
            "100% Extra Virgin Olive Oil",
            "8.5 oz",
            "Iberia",
            3.26,
            16,
            18,
        ),
        new Product(
            "Baking",
            "Chocolate Chunk Muffin Mix",
            "18.25 OZ Box",
            "Krusteaz",
            2.97,
            6,
            14,
        ),
        new Product(
            "Baking",
            "Organic Coconut Flour",
            "36 oz",
            "Great Value Organic",
            7.83,
            13,
            8,
        ),
        new Product(
            "Baking",
            "Easy Pumpkin Pie Mix",
            "30 oz",
            "Libby's",
            3.28,
            10,
            6,
        ),
        new Product(
            "Baking",
            "Vanilla Frosting",
            "15.6 Oz Tub",
            "Pillsbury",
            1.74,
            15,
            15,
        ),
        new Product(
            "Baking",
            "Gluten Free Chocolate Frosting",
            "16 oz",
            "Betty Crocker",
            1.58,
            9,
            12,
        ),
        new Product(
            "Meat & Seafood",
            "Black Bean Burger Patties Plant Based",
            "1/4 lb 2Ct",
            "Gardein",
            3.84,
            2,
            10,
        ),
        new Product(
            "Meat & Seafood",
            "Peeled Tail on Extra Large Shrimp",
            "12 Oz ",
            "Walmart Seafood",
            5.84,
            8,
            7,
        ),
        new Product(
            "Meat & Seafood",
            "All Natural Fresh Bone In Chicken Thighs",
            "4.75 - 6.0 lb",
            "Tyson",
            9.89,
            4,
            16,
        ),
        new Product(
            "Meat & Seafood",
            "Cracked Pepper Turkey Breast",
            "1 package1 package",
            "Prima Della",
            5.44,
            14,
            5,
        ),
        new Product(
            "Meat & Seafood",
            "Meatloaf with Tomato Sauce Refrigerated Entre",
            "15 oz",
            "Hormel",
            6.97,
            10,
            9,
        ),
        new Product(
            "Meat & Seafood",
            "Country Style Ribs",
            "1.25 - 2.99 lb",
            "Fresh Beef",
            12.2,
            16,
            4,
        ),
        new Product(
            "Meat & Seafood",
            "Beef Smoked Sausage Links",
            "13.5 oz, 6 Ct",
            "Hillshire Farm",
            2.98,
            14,
            13,
        ),
        new Product(
            "Meat & Seafood",
            "Italian Garlic & Fennel Plant-Based Sausage",
            "1 package",
            "Field Roast",
            5.33,
            13,
            8,
        ),
        new Product(
            "Meat & Seafood",
            "Hot Italian Pork Sausage",
            "19 oz., 1.19lb. (Fresh)",
            "Premio Foods",
            4.78,
            1,
            11,
        ),
        new Product(
            "Candy",
            "Mexican Chili Lollipops",
            "15.8 oz Bag",
            "Gudu",
            2.97,
            2,
            17,
        ),
        new Product(
            "Candy",
            "Polar Ice Sugar Free Chewing Gum",
            "15 ct (3 Pack)",
            "Extra",
            3.48,
            5,
            24,
        ),
        new Product(
            "Candy",
            "Milk Chocolate with Almonds Bar",
            "1.45 Oz",
            "Hershey's",
            1.14,
            11,
            35,
        ),
        new Product(
            "Candy",
            "Twist 4 Assorted Flavors Gum",
            "16 Oz",
            "Dubble Bubble",
            2.68,
            2,
            19,
        ),
        new Product(
            "Candy",
            "Pink Buttermints",
            "2.75 lbs",
            "Party Sweets",
            10.14,
            12,
            6,
        ),
        new Product(
            "Candy",
            "Halloween Candy Variety Pack",
            "170 Ct Bag, 62.02oz",
            "Mixed",
            16.98,
            4,
            22,
        ),
        new Product(
            "Candy",
            "Chewy Candy Sticks",
            "7.78 oz 21ct",
            "Starburst",
            3.78,
            16,
            18,
        ),
        new Product(
            "Snacks",
            "Organic Sesame Street Peanut Butter Baked Corn Puffs",
            "2.5 oz Bag",
            "Earth's Best",
            3.63,
            11,
            13,
        ),
        new Product(
            "Snacks",
            "Potato Crisps Chips, Variety Pack",
            "16 Ct, 22 Oz, Pack",
            "Pringles",
            13.16,
            8,
            9,
        ),
        new Product(
            "Snacks",
            "Chunky Habanero Salsa",
            "15.5 oz Jar",
            "Tostitos",
            5.38,
            4,
            16,
        ),
        new Product(
            "Snacks",
            "Caramel Almond & Sea Salt",
            "1.4 Oz, 12 Count",
            "KIND Bars",
            15.46,
            4,
            7,
        ),
        new Product(
            "Snacks",
            "Gluten-Free Sea Salt Microwave Popcorn",
            "2.8 oz, 6 Count",
            "SkinnyPop",
            4.84,
            11,
            18,
        ),
        new Product(
            "Snacks",
            "Beef Jerky, Hickory Smoked",
            "2.85oz",
            "Jack Link's",
            4.98,
            3,
            11,
        ),
        new Product(
            "Snacks",
            "Glacier Ranch Tortilla Chips",
            "9.75 oz",
            "Great Value",
            1.74,
            2,
            27,
        ),
        new Product(
            "Dairy & Eggs",
            "Skyr, Coconut",
            "5.3 Ounce",
            "Icelandic Provisions",
            1.48,
            1,
            14,
        ),
        new Product(
            "Dairy & Eggs",
            "Strawberry Cheesecake Snacks",
            "2 ct Pack, 3.25 oz Cups",
            "Philadelphia",
            2.98,
            8,
            0,
        ),
        new Product(
            "Dairy & Eggs",
            "Light Spread",
            "15 oz",
            "I Can't Believe It's Not Butter!",
            3.98,
            4,
            9,
        ),
        new Product(
            "Dairy & Eggs",
            "Butter with Olive Oil and Sea Salt",
            "7 oz",
            "Land O'Lakes",
            2.37,
            16,
            18,
        ),
        new Product(
            "Dairy & Eggs",
            "Liquid Hazelnut Sugar Free Coffee Creamer",
            "32 oz",
            "Coffeemate",
            3.98,
            2,
            11,
        ),
        new Product(
            "Dairy & Eggs",
            "Organic YoBaby Apple & Blueberry Baby Yogurt with Probiotics",
            "6-4 oz. Cups",
            "Stonyfield Farm",
            4.33,
            16,
            7,
        ),
        new Product(
            "Bakery & Bread",
            "Small Fajita Flour Tortillas",
            "22.5 oz",
            "Great Value",
            1.98,
            15,
            22,
        ),
        new Product(
            "Bakery & Bread",
            "Gluten Free Bread",
            "18 oz Loaf",
            "Canyon Bakehouse",
            6.18,
            8,
            6,
        ),
        new Product(
            "Bakery & Bread",
            "Plain Cake Donuts",
            "2 Count",
            "Freshness Guaranteed",
            1.46,
            2,
            18,
        ),
        new Product(
            "Bakery & Bread",
            "Pecan Tiny Pies",
            "16.2 oz, 16 Count",
            "Freshness Guaranteed",
            5.94,
            2,
            10,
        ),
        new Product(
            "Bakery & Bread",
            "Whole Grains Healthy Multi-Grain Bread",
            "24 oz",
            "Arnold",
            3.97,
            4,
            14,
        ),
        new Product(
            "Bakery & Bread",
            "Sesame French Bread",
            "14 oz",
            "Freshness Guaranteed",
            1.78,
            16,
            20,
        ),
        new Product(
            "Bakery & Bread",
            "SNOBALLS Single Serve",
            "2 count, 3.5 oz",
            "Hostess",
            1.58,
            4,
            26,
        ),
        new Product(
            "Bakery & Bread",
            "Vanilla Strawberry Ice Cream Krunch Cake",
            "40 oz",
            "Friendly's",
            14.98,
            2,
            5,
        ),
        new Product(
            "Bakery & Bread",
            "Assorted Sweet Rolls",
            "24 oz, 6 Rolls",
            "Freshness Guaranteed",
            3.98,
            14,
            15,
        ),
        new Product(
            "Bakery & Bread",
            "Texas Toast Bread",
            "22 oz.",
            "Aunt Millie's",
            2.14,
            10,
            17,
        ),
        new Product(
            "Breakfast & Cereal",
            "Green Tea, Lemon Ginseng",
            "1 package",
            "Lipton",
            2.78,
            5,
            19,
        ),
        new Product(
            "Breakfast & Cereal",
            "Queso Fresco Fresh Crumbling Cheese",
            "24 Oz",
            "La Morenita",
            6.22,
            8,
            8,
        ),
        new Product(
            "Breakfast & Cereal",
            "Old Fashioned Oatmeal, Whole Grain",
            "42 oz",
            "Quaker",
            5.68,
            1,
            13,
        ),
        new Product(
            "Breakfast & Cereal",
            "Instant Oatmeal, Variety",
            "12.1 Oz, 12 Count",
            "Quaker",
            3.23,
            8,
            16,
        ),
        new Product(
            "Breakfast & Cereal",
            "Mini Croissants, Chocolate, Non-GMO",
            "2.29oz (Pack of 4 Pouches)",
            "7DAYS",
            3.68,
            1,
            21,
        ),
        new Product(
            "Breakfast & Cereal",
            "Original Cream Cheese Spread",
            "12 oz Tub",
            "Philadelphia",
            5.78,
            6,
            11,
        ),
        new Product(
            "Breakfast & Cereal",
            "Go-Gurt, Low Fat Yogurt, Berry & Strawberry Variety Pack",
            "32 oz",
            "Yoplait",
            4.97,
            6,
            14,
        ),
        new Product(
            "Breakfast & Cereal",
            "100% Orange Juice",
            "64 oz",
            "Great Value",
            2.98,
            13,
            23,
        ),
        new Product(
            "Breakfast & Cereal",
            "Organic Whipped Buttery Spread",
            "13 oz.",
            "Earth Balance",
            5.73,
            2,
            9,
        ),
        new Product(
            "Breakfast & Cereal",
            "Croissant Sandwiches Sausage Egg and Cheese",
            "4 Count",
            "Great Value",
            5.78,
            3,
            0,
        ),
        new Product(
            "Pantry",
            "Zesty Robusto Italian Dressing",
            "15 oz",
            "Wish-Bone",
            2.58,
            9,
            15,
        ),
        new Product(
            "Pantry",
            "Sunny Cranberry Pepitas Salad Topping",
            "5.5oz",
            "Salad Pizazz!",
            2.98,
            3,
            10,
        ),
        new Product(
            "Pantry",
            "Chipotle Peppers in Adobo Sauce",
            "7.0 oz",
            "GOYA",
            2.18,
            8,
            18,
        ),
        new Product(
            "Pantry",
            "Real Bacon Pieces",
            "9 oz",
            "Great Value",
            5.72,
            15,
            12,
        ),
        new Product(
            "Pantry",
            "Peach Halves",
            "29 oz Can",
            "Great Value",
            2.44,
            10,
            16,
        ),
        new Product(
            "Pantry",
            "Mango Habanero",
            "1 package",
            "Buffalo Wild Wings",
            3.58,
            5,
            11,
        ),
        new Product(
            "Pantry",
            "Organic Creamy California Raw Almond Butter",
            "12 oz",
            "MaraNatha",
            16.84,
            4,
            5,
        ),
        new Product(
            "Pantry",
            "Southwest Style Salad with Chicken",
            "1 package",
            "Marketside",
            4.47,
            2,
            8,
        ),
        new Product(
            "Pantry",
            "Mediterranean Pitted Olive Mix",
            "1 package",
            "Asaro",
            5.99,
            9,
            7,
        ),
        new Product(
            "Coffee",
            "Vanilla Flavored Coffee, Ground Coffee",
            "11 oz",
            "Starbucks",
            8.98,
            14,
            13,
        ),
        new Product(
            "Coffee",
            "Baking Blend, Sugar Substitute",
            "12 oz. Bag",
            "Whole Earth Sweetener",
            7.68,
            15,
            8,
        ),
        new Product(
            "Coffee",
            "Organic Powdered Raw Cane Sugar",
            "16 oz Pouch",
            "Florida Crystals",
            3.12,
            14,
            20,
        ),
        new Product(
            "Coffee",
            "Cold Cup with Cold Brew Birthday Everyday Gift",
            "1 package",
            "Starbucks",
            13.98,
            14,
            4,
        ),
        new Product(
            "Coffee",
            "French Vanilla Instant Cappuccino Coffee Drink Mix",
            "16 Oz Canister",
            "Hills Bros. Coffee",
            3.72,
            13,
            0,
        ),
        new Product(
            "Coffee",
            "Caramel Macchiato Iced Coffee",
            "64 Oz.",
            "International Delight",
            4.28,
            8,
            14,
        ),
        new Product(
            "Coffee",
            "French Vanilla Coffee Creamer Singles",
            "48 Count",
            "International Delight",
            5.12,
            11,
            19,
        ),
        new Product(
            "Frozen",
            "Dark Sweet Cherries, Frozen, Pitted",
            "16 oz",
            "Great Value",
            3.88,
            12,
            17,
        ),
        new Product(
            "Frozen",
            "Dairy Free Meatless Pepperoni Gluten Free Pizza",
            "16.7oz",
            "Daiya",
            6.94,
            13,
            9,
        ),
        new Product(
            "Frozen",
            "Ezekiel 4:9 Sprouted Whole Grain Bread",
            "24oz",
            "Food for Life",
            6.18,
            9,
            6,
        ),
        new Product(
            "Frozen",
            "Home Menu Chicken Lo Mein Skillet Meal",
            "22 OZ",
            "P.F. Chang's",
            7.78,
            15,
            0,
        ),
        new Product(
            "Frozen",
            "Cauliflower Crust Margherita",
            "1 package",
            "Great Value",
            4.96,
            9,
            10,
        ),
        new Product(
            "Frozen",
            "100% Beef Sliced Steaks",
            "31.5 oz",
            "Steak-umm",
            10.56,
            1,
            8,
        ),
        new Product(
            "Frozen",
            "Big Burrito Red Hot Beef",
            "1 package",
            "Tina's",
            1.27,
            2,
            28,
        ),
        new Product(
            "Frozen",
            "Pizza Rolls, Triple Cheese Flavored",
            "24.8 oz",
            "Totino's",
            4.98,
            11,
            0,
        ),
        new Product(
            "Frozen",
            "Supreme, Rising Crust Pizza",
            "31.4 oz",
            "DiGiorno",
            6.92,
            16,
            14,
        ),
        new Product(
            "Fresh Produce",
            "Watermelon Chunks",
            "42 oz",
            "Marketside",
            8.97,
            7,
            6,
        ),
        new Product(
            "Fresh Produce",
            "Organic Garlic Sleeve",
            "3 Count",
            "Spice World",
            2.98,
            8,
            15,
        ),
        new Product(
            "Fresh Produce",
            "Napa Cabbage",
            "1 item",
            "No Name",
            3.97,
            4,
            9,
        ),
        new Product(
            "Fresh Produce",
            "Rose Plus Bouquet",
            "1 bunch",
            "No Name",
            9.97,
            4,
            4,
        ),
        new Product(
            "Fresh Produce",
            "Organic Asparagus",
            "1 bunch",
            "No Name",
            5.96,
            8,
            7,
        ),
        new Product(
            "Fresh Produce",
            "Chunky Blue Cheese Dressing & Dip",
            "13 oz Jar",
            "Litehouse",
            3.96,
            5,
            11,
        ),
        new Product(
            "Fresh Produce",
            "Minced Garlic",
            "32 Oz",
            "Great Value",
            7.76,
            13,
            19,
        ),
        new Product(
            "Fresh Produce",
            "White Nectarines",
            "1 item",
            "No Name",
            1.06,
            11,
            8,
        ),
        new Product(
            "Fresh Produce",
            "Fresh Long English Cucumber",
            "1 item",
            "No Name",
            1.38,
            8,
            12,
        ),
        new Product(
            "Alcohol",
            "Beer",
            "30 Pack 12 oz",
            "Bud Ice",
            19.98,
            13,
            18,
        ),
        new Product(
            "Alcohol",
            "Hard Seltzer Variety Pack 1",
            "12 Pack, 12 oz Cans",
            "Vizzy",
            17.98,
            9,
            14,
        ),
        new Product(
            "Alcohol",
            "Bourbon Barrel Aged Cabernet Sauvignon Red Wine",
            "750 mL Bottle",
            "Robert Mondavi Private Selection",
            11.98,
            13,
            9,
        ),
        new Product(
            "Alcohol",
            "White Wine",
            "3 L Box",
            "Black Box",
            18.98,
            8,
            7,
        ),
        new Product(
            "Alcohol",
            "Cabernet Sauvignon Wine",
            "750 mL",
            "JUSTIN",
            24.48,
            14,
            5,
        ),
        new Product(
            "Alcohol",
            "Beer",
            "6 Pack, 16 oz Cans",
            "Old Style",
            6.73,
            14,
            20,
        ),
        new Product(
            "Alcohol",
            "Petit Petite Wine",
            "750 mL",
            "Michael David Winery",
            13.48,
            11,
            6,
        ),
        new Product(
            "Alcohol",
            "Prosecco Sparkling White Wine",
            "375ml",
            "LA MARCA",
            9.98,
            14,
            11,
        ),
        new Product(
            "Alcohol",
            "Merlot Wine",
            "1.5 L",
            "Barefoot",
            9.98,
            4,
            8,
        ),
        new Product(
            "Alcohol",
            "Light Beer",
            "30 Pack, 12 oz Cans",
            "Keystone",
            17.99,
            3,
            0,
        ),
    );
}