name: Python Codestyle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/python-codestyle.yml'
      - 'recipes/**/*.py'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/python-codestyle.yml'
      - 'recipes/**/*.py'

jobs:
  check-python-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install flake8 pep8-naming

    - name: Check python codestyle
      run: flake8 --ignore=F401,F403,F405 --max-line-length=120 recipes/
